apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: photo-album-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/kadam12g/photo-album-app.git
    targetRevision: HEAD
    path: k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: photo-album
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
