apiVersion: apps/v1
kind: Deployment
metadata:
  name: photo-album-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: photo-album-app
  template:
    metadata:
      labels:
        app: photo-album-app
    spec:
      containers:
      - name: photo-album-app
        image: ${GITHUB_REPOSITORY}:${GITHUB_SHA}
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
