name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint-and-build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          # This ensures we get the full history for pushing changes back
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          pip install -r requirements.txt

      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/photo-album-app:latest
            ghcr.io/${{ github.repository }}/photo-album-app:${{ github.sha }}
          cache-from: type=registry,ref=ghcr.io/${{ github.repository }}/photo-album-app:latest
          cache-to: type=inline

      - name: Update Kubernetes manifest
        run: |
          IMAGE_TAG="ghcr.io/${{ github.repository }}/photo-album-app:${{ github.sha }}"
          echo "Using image tag: ${IMAGE_TAG}"
          sed -i "s|image: .*|image: ${IMAGE_TAG}|g" k8s/deployment.yaml

      - name: Set up Git
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          
      - name: Commit and push changes
        if: github.event_name != 'pull_request'
        run: |
          git add k8s/deployment.yaml
          git commit -m "Update image tag to ${{ github.sha }}" || echo "No changes to commit"
          git push
