name: Build and Deploy


on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  tailscale_test:
    runs-on: ubuntu-latest
    steps:
      - name: Connect to Tailscale
        uses: tailscale/github-action@v3
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
          tags: tag:ci

      - name: Debug Tailscale
        run: |
          echo "Tailscale status:"
          tailscale status
          
          echo "Network interfaces:"
          ip addr
          
          echo "Routing table:"
          ip route
          
          echo "Testing with curl:"
          # Replace "server-hostname" with your actual Tailscale hostname
          curl -m 10 http://${{ secrets.SERVER_HOSTNAME }}:8080 || echo "Curl failed"

  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: ghcr.io/${{ github.repository }}:${{ github.sha }}
        
    - name: Connect to Tailscale
      uses: tailscale/github-action@v3
      with:
        oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
        oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
        tags: tag:ci

    - name: Setup kubectl
      uses: azure/setup-kubectl@v3
      
    - name: Create kubeconfig
      run: |
        echo "${{ secrets.KUBECONFIG }}" > kubeconfig.yaml
      
    - name: Update deployment image
      run: |
        sed -i "s|\${GITHUB_REPOSITORY}:\${GITHUB_SHA}|ghcr.io/${{ github.repository }}:${{ github.sha }}|" kubernetes/deployment.yaml

    - name: Verify Tailscale and Kubernetes connectivity
      run: |
        # Check network interfaces
        echo "Checking network interfaces:"
        ip addr show
        
        # Check routing
        echo -e "\nChecking routes:"
        ip route
        
        # Check if we can reach the API server
        echo -e "\nChecking API server connectivity with curl:"
        curl -k -v https://${{ secrets.SERVER_HOSTNAME }}:6443/version || echo "Curl failed but continuing"
        
        # Test kubectl connectivity with basic commands
        echo -e "\nTesting kubectl connectivity:"
        kubectl --kubeconfig=kubeconfig.yaml version
        kubectl --kubeconfig=kubeconfig.yaml get namespaces
      
    - name: Deploy to Kubernetes
      run: |
        kubectl --kubeconfig=kubeconfig.yaml apply -f kubernetes/deployment.yaml --validate=false
        kubectl --kubeconfig=kubeconfig.yaml apply -f kubernetes/service.yaml --validate=false
        
    - name: Wait for deployment
      run: |
        kubectl --kubeconfig=kubeconfig.yaml rollout status deployment/photo-album-app
        
    - name: Display service info
      run: |
        kubectl --kubeconfig=kubeconfig.yaml get svc photo-album-app -o wide
        
